tests/getopt: suppress clang nitpick
In the context of

    while ((ch = GETOPT...
            fprintf(stderr, "Option being processed...
            WARNING_UNINITIALIZED_SUPPRESS
            GETOPT_SWITCH(ch) {

the GETOPT_SWITCH(ch) contains a few variable declarations, which leads
clang -Weverything to complain that:

    main.c:42:3: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]

I'm tempted to disable that warning globally (since we're using C99),
but given that:
  - this is the only such warning,
  - it only occurs in the test suite,
  - our "house style" is to declare variables before statements anyway,
  - and we have a "suppress warnings" option right there,
I figured that it's enough to disable it locally.