cpusupport: avoid implicit conversion
Compiling with `clang -Werror -Weverything` produced:

    Checking if compiler supports X86 CPUID_COUNT feature... no

because

    ./cpusupport/Build/cpusupport-X86-CPUID_COUNT.c:9:10: error: implicit conversion
          changes signedness: 'unsigned int' to 'int' [-Werror,-Wsign-conversion]
            return (a);
            ~~~~~~  ^